package model

import "fmt"

// https://www.postgresql.org/docs/current/catalog-pg-attribute.html

type ColumnIdentity byte

func (b ColumnIdentity) IsIdentityColumn() bool {
	return b != 0
}

func (b ColumnIdentity) IsGeneratedAlways() bool {
	return b == 'a'
}

func (b ColumnIdentity) IsGeneratedByDefault() bool {
	return b == 'd'
}

type ColumnGenerated byte

func (b ColumnGenerated) IsGeneratedColumn() bool {
	return b != 0
}

func (b ColumnGenerated) IsStoredGeneratedColumn() bool {
	return b == 's'
}

func (b ColumnGenerated) IsVirtualGeneratedColumn() bool {
	return b == 'v'
}

type Column struct {
	Name        string
	RenameFrom  *string
	TypeName    string
	NotNull     bool
	NotNullName *string
	Default     *string
	Identity    ColumnIdentity
	Generated   ColumnGenerated
	// Collation in quoted SQL form, ready to follow COLLATE
	// (e.g. `pg_catalog."C"`). nil for the default collation.
	Collation   *string
	StorageType string
	Comment     *string
}

func (col *Column) String() string {
	return fmt.Sprintf("%#v", *col)
}
