package model

import "fmt"

// https://www.postgresql.org/docs/current/catalog-pg-attribute.html

type ColumnIdentity byte

// MarshalJSON writes the identity kind as a word instead of the pg_attribute
// character, since the JSON is read outside pistachio.
func (b ColumnIdentity) MarshalJSON() ([]byte, error) {
	switch b {
	case 'a':
		return []byte(`"always"`), nil
	case 'd':
		return []byte(`"by_default"`), nil
	default:
		return []byte(`""`), nil
	}
}

func (b ColumnIdentity) IsIdentityColumn() bool {
	return b != 0
}

func (b ColumnIdentity) IsGeneratedAlways() bool {
	return b == 'a'
}

func (b ColumnIdentity) IsGeneratedByDefault() bool {
	return b == 'd'
}

type ColumnGenerated byte

// MarshalJSON writes the generation kind as a word instead of the
// pg_attribute character, since the JSON is read outside pistachio.
func (b ColumnGenerated) MarshalJSON() ([]byte, error) {
	switch b {
	case 's':
		return []byte(`"stored"`), nil
	case 'v':
		return []byte(`"virtual"`), nil
	default:
		return []byte(`""`), nil
	}
}

func (b ColumnGenerated) IsGeneratedColumn() bool {
	return b != 0
}

func (b ColumnGenerated) IsStoredGeneratedColumn() bool {
	return b == 's'
}

func (b ColumnGenerated) IsVirtualGeneratedColumn() bool {
	return b == 'v'
}

type Column struct {
	Name       string  `json:"name"`
	RenameFrom *string `json:"rename_from,omitempty"`
	TypeName   string  `json:"type"`
	// SerialSequence names the sequence a serial column owns, schema
	// qualified. Only the catalog fills it: a type name says the column is a
	// serial, but not what PostgreSQL called its sequence. nil otherwise.
	SerialSequence *string        `json:"serial_sequence,omitempty"`
	NotNull        bool           `json:"not_null,omitzero"`
	NotNullName    *string        `json:"not_null_name,omitempty"`
	Default        *string        `json:"default,omitempty"`
	Identity       ColumnIdentity `json:"identity,omitzero"`
	// IdentitySeq holds the sequence parameters of an identity column. It is
	// nil when the column is not an identity column.
	IdentitySeq *IdentitySequence `json:"identity_sequence,omitempty"`
	Generated   ColumnGenerated   `json:"generated,omitzero"`
	// Collation in quoted SQL form, ready to follow COLLATE
	// (e.g. `pg_catalog."C"`). nil for the default collation.
	Collation *string `json:"collation,omitempty"`
	// StorageType is the column's TOAST strategy: plain, external, extended
	// or main. The desired side holds what the definition wrote, empty when
	// it wrote nothing or wrote DEFAULT.
	StorageType string `json:"storage_type,omitempty"`
	// TypeStorage is the strategy the column's type defaults to. Only the
	// catalog fills it, since the desired side cannot know it, and the diff
	// resolves an unwritten StorageType against it.
	TypeStorage string `json:"type_storage,omitempty"`
	// Compression is the column's TOAST compression method (pglz, lz4), empty
	// when the column carries none and default_toast_compression decides.
	Compression string  `json:"compression,omitempty"`
	Comment     *string `json:"comment,omitempty"`
}

func (col *Column) String() string {
	return fmt.Sprintf("%#v", *col)
}
