package model

import "fmt"

// https://www.postgresql.org/docs/current/catalog-pg-attribute.html

type ColumnIdentity byte

// MarshalJSON writes the identity kind as a word instead of the pg_attribute
// character, since the JSON is read outside pistachio.
func (b ColumnIdentity) MarshalJSON() ([]byte, error) {
	switch b {
	case 'a':
		return []byte(`"always"`), nil
	case 'd':
		return []byte(`"by_default"`), nil
	default:
		return []byte(`""`), nil
	}
}

func (b ColumnIdentity) IsIdentityColumn() bool {
	return b != 0
}

func (b ColumnIdentity) IsGeneratedAlways() bool {
	return b == 'a'
}

func (b ColumnIdentity) IsGeneratedByDefault() bool {
	return b == 'd'
}

type ColumnGenerated byte

// MarshalJSON writes the generation kind as a word instead of the
// pg_attribute character, since the JSON is read outside pistachio.
func (b ColumnGenerated) MarshalJSON() ([]byte, error) {
	switch b {
	case 's':
		return []byte(`"stored"`), nil
	case 'v':
		return []byte(`"virtual"`), nil
	default:
		return []byte(`""`), nil
	}
}

func (b ColumnGenerated) IsGeneratedColumn() bool {
	return b != 0
}

func (b ColumnGenerated) IsStoredGeneratedColumn() bool {
	return b == 's'
}

func (b ColumnGenerated) IsVirtualGeneratedColumn() bool {
	return b == 'v'
}

type Column struct {
	Name       string  `json:"name"`
	RenameFrom *string `json:"rename_from"`
	TypeName   string  `json:"type"`
	// RetypeUsing is the USING expression of a type change, set by
	// -- pista:retype-using. Only the desired side sets it, and it only shapes
	// the SET DATA TYPE statement.
	RetypeUsing *string `json:"-"`
	// SerialSequence is the schema-qualified name of the sequence that the
	// column owns and takes its default from. Only the catalog sets it; nil
	// otherwise. The type name is a serial type only when the sequence has
	// the default name. Default holds the nextval() in both cases. A serial
	// type does not write it, because PostgreSQL rejects a default with it.
	SerialSequence *string        `json:"serial_sequence"`
	NotNull        bool           `json:"not_null"`
	NotNullName    *string        `json:"not_null_name"`
	Default        *string        `json:"default"`
	Identity       ColumnIdentity `json:"identity"`
	// IdentitySeq holds the sequence parameters of an identity column. It is
	// nil when the column is not an identity column.
	IdentitySeq *IdentitySequence `json:"identity_sequence"`
	Generated   ColumnGenerated   `json:"generated"`
	// Collation in quoted SQL form, ready to follow COLLATE
	// (e.g. `pg_catalog."C"`). nil for the default collation.
	Collation *string `json:"collation"`
	// StorageType is the column's TOAST strategy: plain, external, extended
	// or main. The desired side holds what the definition wrote, empty when
	// it wrote nothing or wrote DEFAULT.
	StorageType string `json:"storage_type"`
	// TypeStorage is the strategy the column's type defaults to. Only the
	// catalog fills it, since the desired side cannot know it, and the diff
	// resolves an unwritten StorageType against it.
	TypeStorage string `json:"type_storage"`
	// Compression is the column's TOAST compression method (pglz, lz4), empty
	// when the column carries none and default_toast_compression decides.
	Compression string  `json:"compression"`
	Comment     *string `json:"comment"`
}

func (col *Column) String() string {
	return fmt.Sprintf("%#v", *col)
}

// IsSerialType reports whether a type name is one of the serial pseudo-types.
func IsSerialType(typeName string) bool {
	switch typeName {
	case "serial", "bigserial", "smallserial":
		return true
	}
	return false
}
