package model_test

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/winebarrel/orderedmap/v2"
	"github.com/winebarrel/pistachio/model"
)

func newTable(schema, name string) *model.Table {
	return &model.Table{
		Schema:      schema,
		Name:        name,
		Columns:     orderedmap.New[string, *model.Column](),
		Constraints: orderedmap.New[string, *model.Constraint](),
		ForeignKeys: orderedmap.New[string, *model.ForeignKey](),
		Indexes:     orderedmap.New[string, *model.Index](),
		Policies:    orderedmap.New[string, *model.Policy](),
	}
}

func TestTable_RLSSQL_Empty(t *testing.T) {
	tbl := newTable("public", "users")
	assert.Empty(t, tbl.RLSSQL())
}

func TestTable_RLSSQL_EnableOnly(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.RowSecurity = true
	assert.Equal(t, "ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;", tbl.RLSSQL())
}

func TestTable_RLSSQL_EnableAndForce(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.RowSecurity = true
	tbl.ForceRowSecurity = true
	assert.Equal(t,
		"ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;\n"+
			"ALTER TABLE public.users FORCE ROW LEVEL SECURITY;",
		tbl.RLSSQL())
}

func TestTable_RLSSQL_WithPolicies(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.RowSecurity = true
	using := "owner = current_user"
	tbl.Policies.Set("p", &model.Policy{
		Name: "p", Schema: "public", Table: "users",
		Permissive: true, Command: 'r', Using: &using,
	})
	got := tbl.RLSSQL()
	assert.Contains(t, got, "ENABLE ROW LEVEL SECURITY;")
	assert.Contains(t, got, "CREATE POLICY p ON public.users FOR SELECT USING (owner = current_user);")
}

// nil-Policies guard: an older Table built without orderedmap-init must not
// panic on RLSSQL even though the parser/catalog now always initialize it.
func TestTable_RLSSQL_NilPolicies(t *testing.T) {
	tbl := &model.Table{Schema: "public", Name: "users"}
	assert.Empty(t, tbl.RLSSQL())
}

func TestTableToSQL_IncludesRLS(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.Columns.Set("id", &model.Column{Name: "id", TypeName: "integer", NotNull: true})
	tbl.RowSecurity = true
	out := model.TableToSQL(tbl)
	assert.Contains(t, out, "CREATE TABLE public.users")
	assert.Contains(t, out, "ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;")
}

func TestTable_FQTN(t *testing.T) {
	tbl := newTable("public", "users")
	assert.Equal(t, "public.users", tbl.FQTN())
}

func TestTable_SQL_simple(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.Columns.Set("id", &model.Column{Name: "id", TypeName: "integer", NotNull: true})
	tbl.Constraints.Set("users_pkey", &model.Constraint{Name: "users_pkey", Definition: "PRIMARY KEY (id)"})

	expected := `CREATE TABLE public.users (
    id integer NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);`
	assert.Equal(t, expected, tbl.SQL())
}

func TestTable_SQL_namedNotNull(t *testing.T) {
	name := "users_email_nn"
	tbl := newTable("public", "users")
	tbl.Columns.Set("email", &model.Column{Name: "email", TypeName: "text", NotNull: true, NotNullName: &name})

	assert.Contains(t, tbl.SQL(), "email text CONSTRAINT users_email_nn NOT NULL")
}

func TestTable_SQL_namedNotNull_identityColumnSuppresses(t *testing.T) {
	// Identity columns are implicitly NOT NULL; the SQL renderer must not emit
	// either the "NOT NULL" tail or the CONSTRAINT name on identity columns.
	name := "users_id_nn"
	tbl := newTable("public", "users")
	tbl.Columns.Set("id", &model.Column{Name: "id", TypeName: "integer", NotNull: true, NotNullName: &name, Identity: model.ColumnIdentity('a')})

	out := tbl.SQL()
	assert.Contains(t, out, "GENERATED ALWAYS AS IDENTITY")
	assert.NotContains(t, out, "CONSTRAINT users_id_nn")
	assert.NotContains(t, out, "NOT NULL")
}

func TestTable_SQL_unlogged(t *testing.T) {
	tbl := newTable("public", "temp_data")
	tbl.Unlogged = true
	tbl.Columns.Set("id", &model.Column{Name: "id", TypeName: "integer"})

	assert.Contains(t, tbl.SQL(), "CREATE UNLOGGED TABLE")
}

func TestTable_SQL_withDefault(t *testing.T) {
	tbl := newTable("public", "users")
	def := "0"
	tbl.Columns.Set("age", &model.Column{Name: "age", TypeName: "integer", Default: &def})

	assert.Contains(t, tbl.SQL(), "DEFAULT 0")
}

func TestTable_SQL_withCollation(t *testing.T) {
	tbl := newTable("public", "users")
	coll := `"en_US"`
	tbl.Columns.Set("name", &model.Column{Name: "name", TypeName: "text", Collation: &coll})

	assert.Contains(t, tbl.SQL(), `COLLATE "en_US"`)
}

func TestTable_SQL_identityAlways(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.Columns.Set("id", &model.Column{Name: "id", TypeName: "integer", Identity: model.ColumnIdentity('a')})

	assert.Contains(t, tbl.SQL(), "GENERATED ALWAYS AS IDENTITY")
}

func TestTable_SQL_identityByDefault(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.Columns.Set("id", &model.Column{Name: "id", TypeName: "integer", Identity: model.ColumnIdentity('d')})

	assert.Contains(t, tbl.SQL(), "GENERATED BY DEFAULT AS IDENTITY")
}

func TestTable_SQL_generatedStored(t *testing.T) {
	tbl := newTable("public", "users")
	def := "first_name || ' ' || last_name"
	tbl.Columns.Set("full_name", &model.Column{
		Name:      "full_name",
		TypeName:  "text",
		Generated: model.ColumnGenerated('s'),
		Default:   &def,
	})

	sql := tbl.SQL()
	assert.Contains(t, sql, "GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED")
}

func TestTable_SQL_identityNotNull(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.Columns.Set("id", &model.Column{Name: "id", TypeName: "integer", NotNull: true, Identity: model.ColumnIdentity('a')})
	// Identity columns should NOT emit NOT NULL
	assert.NotContains(t, tbl.SQL(), "NOT NULL")
}

func TestTable_SQL_partitioned(t *testing.T) {
	tbl := newTable("public", "events")
	tbl.Partitioned = true
	partDef := "RANGE (created_at)"
	tbl.PartitionDef = &partDef
	tbl.Columns.Set("id", &model.Column{Name: "id", TypeName: "integer"})

	sql := tbl.SQL()
	assert.Contains(t, sql, "PARTITION BY RANGE (created_at)")
}

func TestTable_IsPartitionChild(t *testing.T) {
	parent := "public.events"
	bound := "FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')"

	tbl := newTable("public", "events_2024")
	assert.False(t, tbl.IsPartitionChild())

	tbl.PartitionOf = &parent
	// An INHERITS child carries a parent but no bound.
	assert.False(t, tbl.IsPartitionChild())

	tbl.PartitionBound = &bound
	assert.True(t, tbl.IsPartitionChild())
}

func TestTable_SQL_partitionOf_withBound(t *testing.T) {
	tbl := newTable("public", "events_2024")
	parent := "public.events"
	bound := "FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')"
	tbl.PartitionOf = &parent
	tbl.PartitionBound = &bound

	sql := tbl.SQL()
	assert.Contains(t, sql, "PARTITION OF public.events")
	assert.Contains(t, sql, "FOR VALUES FROM")
}

func TestTable_SQL_partitionOf_withBound_tablespace(t *testing.T) {
	tbl := newTable("public", "events_2024")
	parent := "public.events"
	bound := "FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')"
	ts := "fast_ssd"
	tbl.PartitionOf = &parent
	tbl.PartitionBound = &bound
	tbl.TableSpace = &ts

	sql := tbl.SQL()
	assert.Contains(t, sql, "TABLESPACE fast_ssd")
}

func TestTable_SQL_partitionOf_subpartitioned(t *testing.T) {
	tbl := newTable("public", "events_east")
	parent := "public.events"
	bound := "FOR VALUES FROM ('a') TO ('m')"
	partDef := "LIST (kind)"
	tbl.PartitionOf = &parent
	tbl.PartitionBound = &bound
	tbl.Partitioned = true
	tbl.PartitionDef = &partDef

	assert.Equal(t,
		"CREATE TABLE public.events_east PARTITION OF public.events FOR VALUES FROM ('a') TO ('m')\nPARTITION BY LIST (kind);",
		tbl.SQL())
}

func TestTable_SQL_partitionOf_subpartitioned_tablespace(t *testing.T) {
	tbl := newTable("public", "events_east")
	parent := "public.events"
	bound := "FOR VALUES FROM ('a') TO ('m')"
	partDef := "LIST (kind)"
	ts := "fast_ssd"
	tbl.PartitionOf = &parent
	tbl.PartitionBound = &bound
	tbl.Partitioned = true
	tbl.PartitionDef = &partDef
	tbl.TableSpace = &ts

	// PARTITION BY comes before TABLESPACE, as the CREATE TABLE grammar has it.
	assert.Equal(t,
		"CREATE TABLE public.events_east PARTITION OF public.events FOR VALUES FROM ('a') TO ('m')\nPARTITION BY LIST (kind)\nTABLESPACE fast_ssd;",
		tbl.SQL())
}

func TestTable_SQL_partitionOf_inherits(t *testing.T) {
	tbl := newTable("public", "child")
	parent := "public.parent"
	tbl.PartitionOf = &parent
	tbl.Constraints.Set("child_pkey", &model.Constraint{Name: "child_pkey", Definition: "PRIMARY KEY (id)"})

	sql := tbl.SQL()
	assert.Contains(t, sql, "INHERITS (public.parent)")
	assert.Contains(t, sql, "CONSTRAINT child_pkey PRIMARY KEY (id)")
}

func TestTable_SQL_tablespace(t *testing.T) {
	tbl := newTable("public", "users")
	ts := "my_ts"
	tbl.TableSpace = &ts
	tbl.Columns.Set("id", &model.Column{Name: "id", TypeName: "integer"})

	assert.Contains(t, tbl.SQL(), "TABLESPACE my_ts")
}

func TestTable_IdxSQL(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.Indexes.Set("idx_name", &model.Index{Definition: "CREATE INDEX idx_name ON public.users USING btree (name)"})
	assert.Equal(t, "CREATE INDEX idx_name ON public.users USING btree (name);", tbl.IdxSQL())
}

func TestTable_IdxSQL_empty(t *testing.T) {
	tbl := newTable("public", "users")
	assert.Equal(t, "", tbl.IdxSQL())
}

func TestTable_FkSQL(t *testing.T) {
	tbl := newTable("public", "orders")
	tbl.ForeignKeys.Set("fk_user", &model.ForeignKey{
		Constraint: model.Constraint{Name: "fk_user", Definition: "FOREIGN KEY (user_id) REFERENCES public.users(id)", Validated: true},
		Schema:     "public",
		Table:      "orders",
	})
	assert.Contains(t, tbl.FkSQL(), "ALTER TABLE ONLY public.orders ADD CONSTRAINT fk_user")
}

func TestTable_CommentSQL(t *testing.T) {
	tbl := newTable("public", "users")
	comment := "Main users table"
	tbl.Comment = &comment
	colComment := "User name"
	tbl.Columns.Set("name", &model.Column{Name: "name", TypeName: "text", Comment: &colComment})

	sql := tbl.CommentSQL()
	assert.Contains(t, sql, "COMMENT ON TABLE public.users IS 'Main users table';")
	assert.Contains(t, sql, "COMMENT ON COLUMN public.users.name IS 'User name';")
}

func TestTable_CommentSQL_noComments(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.Columns.Set("id", &model.Column{Name: "id", TypeName: "integer"})
	assert.Equal(t, "", tbl.CommentSQL())
}

func TestTablesToSQL(t *testing.T) {
	tables := orderedmap.New[string, *model.Table]()
	tbl := newTable("public", "users")
	tbl.Columns.Set("id", &model.Column{Name: "id", TypeName: "integer", NotNull: true})
	tbl.Constraints.Set("users_pkey", &model.Constraint{Name: "users_pkey", Definition: "PRIMARY KEY (id)"})
	tables.Set("public.users", tbl)

	got := model.TablesToSQL(tables)
	assert.Contains(t, got, "-- public.users")
	assert.Contains(t, got, "CREATE TABLE public.users")
}

func TestTablesToSQL_withIndexAndFK(t *testing.T) {
	tables := orderedmap.New[string, *model.Table]()
	tbl := newTable("public", "orders")
	tbl.Columns.Set("id", &model.Column{Name: "id", TypeName: "integer", NotNull: true})
	tbl.Indexes.Set("idx_user", &model.Index{Definition: "CREATE INDEX idx_user ON public.orders USING btree (user_id)"})
	tbl.ForeignKeys.Set("fk_user", &model.ForeignKey{
		Constraint: model.Constraint{Name: "fk_user", Definition: "FOREIGN KEY (user_id) REFERENCES public.users(id)", Validated: true},
		Schema:     "public",
		Table:      "orders",
	})
	comment := "Orders table"
	tbl.Comment = &comment
	tables.Set("public.orders", tbl)

	got := model.TablesToSQL(tables)
	assert.Contains(t, got, "-- public.orders")
	assert.Contains(t, got, "CREATE TABLE public.orders")
	assert.Contains(t, got, "CREATE INDEX idx_user")
	assert.Contains(t, got, "ADD CONSTRAINT fk_user")
	assert.Contains(t, got, "COMMENT ON TABLE public.orders")
}

func TestTablesToSQL_multipleTables(t *testing.T) {
	tables := orderedmap.New[string, *model.Table]()
	t1 := newTable("public", "a")
	t1.Columns.Set("id", &model.Column{Name: "id", TypeName: "integer"})
	tables.Set("public.a", t1)
	t2 := newTable("public", "b")
	t2.Columns.Set("id", &model.Column{Name: "id", TypeName: "integer"})
	tables.Set("public.b", t2)

	got := model.TablesToSQL(tables)
	assert.Contains(t, got, "-- public.a")
	assert.Contains(t, got, "-- public.b")
}

func TestTable_StorageSQL(t *testing.T) {
	tbl := newTable("public", "docs")
	// A column at its type's own strategy carries nothing.
	tbl.Columns.Set("title", &model.Column{Name: "title", TypeName: "text", StorageType: "extended", TypeStorage: "extended"})
	tbl.Columns.Set("body", &model.Column{Name: "body", TypeName: "text", StorageType: "external", TypeStorage: "extended"})
	tbl.Columns.Set("note", &model.Column{Name: "note", TypeName: "text", StorageType: "extended", TypeStorage: "extended", Compression: "pglz"})

	assert.Equal(t,
		"ALTER TABLE public.docs ALTER COLUMN body SET STORAGE EXTERNAL;\n"+
			"ALTER TABLE public.docs ALTER COLUMN note SET COMPRESSION pglz;",
		tbl.StorageSQL())
}

func TestTable_StorageSQL_Empty(t *testing.T) {
	tbl := newTable("public", "docs")
	tbl.Columns.Set("id", &model.Column{Name: "id", TypeName: "integer", StorageType: "plain", TypeStorage: "plain"})
	assert.Empty(t, tbl.StorageSQL())
}

// A partition child declares no columns of its own and takes the strategy from
// its parent, so the statements belong to the parent alone.
func TestTable_StorageSQL_PartitionChild(t *testing.T) {
	tbl := newTable("public", "docs_1")
	parent := "public.docs"
	bound := "FOR VALUES FROM (0) TO (10)"
	tbl.PartitionOf = &parent
	tbl.PartitionBound = &bound
	tbl.Columns.Set("body", &model.Column{Name: "body", TypeName: "text", StorageType: "external", TypeStorage: "extended"})
	assert.Empty(t, tbl.StorageSQL())
}

func TestSetCompressionSQL_Default(t *testing.T) {
	// An empty method hands the column back to default_toast_compression.
	assert.Equal(t,
		"ALTER TABLE public.docs ALTER COLUMN body SET COMPRESSION default;",
		model.SetCompressionSQL("public.docs", "body", ""))
}

func TestTableToSQL_IncludesStorage(t *testing.T) {
	tbl := newTable("public", "docs")
	tbl.Columns.Set("body", &model.Column{Name: "body", TypeName: "text", StorageType: "main", TypeStorage: "extended"})
	out := model.TableToSQL(tbl)
	assert.Contains(t, out, "CREATE TABLE public.docs")
	assert.Contains(t, out, "ALTER TABLE public.docs ALTER COLUMN body SET STORAGE MAIN;")
}

func TestTable_StorageParamsSQL_empty(t *testing.T) {
	tbl := newTable("public", "users")
	assert.Empty(t, tbl.StorageParamsSQL())

	tbl.StorageParams = model.SortedStorageParams(nil)
	assert.Empty(t, tbl.StorageParamsSQL())
}

func TestTable_StorageParamsSQL_sortedAndQuoted(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.StorageParams = model.SortedStorageParams(map[string]string{
		"toast.autovacuum_enabled": "off",
		"fillfactor":               "70",
		"autovacuum_enabled":       "off",
	})

	assert.Equal(t,
		"WITH (autovacuum_enabled='off', fillfactor='70', toast.autovacuum_enabled='off')",
		tbl.StorageParamsSQL())
}

func TestTable_SQL_storageParams(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.Columns.Set("id", &model.Column{Name: "id", TypeName: "integer", NotNull: true})
	tbl.StorageParams = model.SortedStorageParams(map[string]string{"fillfactor": "70"})

	assert.Equal(t,
		"CREATE TABLE public.users (\n    id integer NOT NULL\n)\nWITH (fillfactor='70');",
		tbl.SQL())
}

func TestTable_SQL_storageParams_partitionOf(t *testing.T) {
	tbl := newTable("public", "events_east")
	parent := "public.events"
	bound := "FOR VALUES FROM ('a') TO ('m')"
	partDef := "LIST (kind)"
	ts := "fast_ssd"
	tbl.PartitionOf = &parent
	tbl.PartitionBound = &bound
	tbl.Partitioned = true
	tbl.PartitionDef = &partDef
	tbl.TableSpace = &ts
	tbl.StorageParams = model.SortedStorageParams(map[string]string{"fillfactor": "60"})

	// WITH sits between PARTITION BY and TABLESPACE, as the grammar has it.
	assert.Equal(t,
		"CREATE TABLE public.events_east PARTITION OF public.events FOR VALUES FROM ('a') TO ('m')\n"+
			"PARTITION BY LIST (kind)\nWITH (fillfactor='60')\nTABLESPACE fast_ssd;",
		tbl.SQL())
}

func TestTable_SQL_storageParams_inherits(t *testing.T) {
	tbl := newTable("public", "child")
	parent := "public.parent"
	tbl.PartitionOf = &parent
	tbl.Constraints.Set("child_pkey", &model.Constraint{Name: "child_pkey", Definition: "PRIMARY KEY (id)"})
	tbl.StorageParams = model.SortedStorageParams(map[string]string{"fillfactor": "65"})

	assert.Equal(t,
		"CREATE TABLE public.child(\n    CONSTRAINT child_pkey PRIMARY KEY (id))\n"+
			"INHERITS (public.parent)\nWITH (fillfactor='65');",
		tbl.SQL())
}

func TestSetStorageParamsSQL(t *testing.T) {
	assert.Equal(t,
		"ALTER TABLE public.users SET (fillfactor='90', toast.autovacuum_enabled='off');",
		model.SetStorageParamsSQL("public.users", []string{"fillfactor='90'", "toast.autovacuum_enabled='off'"}))
}

func TestResetStorageParamsSQL(t *testing.T) {
	assert.Equal(t,
		"ALTER TABLE public.users RESET (autovacuum_enabled, fillfactor);",
		model.ResetStorageParamsSQL("public.users", []string{"autovacuum_enabled", "fillfactor"}))
}

func TestSortedStorageParams(t *testing.T) {
	params := model.SortedStorageParams(map[string]string{"b": "2", "a": "1", "c": "3"})
	assert.Equal(t, []string{"a", "b", "c"}, params.CollectKeys())
	assert.Equal(t, []string{"1", "2", "3"}, params.CollectValues())
}
