package model

import (
	"slices"
	"strings"

	"github.com/winebarrel/orderedmap"
)

type Table struct {
	OID              uint32
	Schema           string
	Name             string
	RenameFrom       *string
	TableSpace       *string
	Unlogged         bool
	Partitioned      bool
	PartitionDef     *string
	PartitionOf      *string
	PartitionBound   *string
	RowSecurity      bool
	ForceRowSecurity bool
	Columns          *orderedmap.Map[string, *Column]
	Constraints      *orderedmap.Map[string, *Constraint]
	ForeignKeys      *orderedmap.Map[string, *ForeignKey]
	Indexes          *orderedmap.Map[string, *Index]
	Policies         *orderedmap.Map[string, *Policy]
	Comment          *string
}

func (t Table) FQTN() string {
	return Ident(t.Schema, t.Name)
}

func (t Table) SQL() string {
	sql := "CREATE "
	if t.Unlogged {
		sql += "UNLOGGED "
	}
	sql += "TABLE " + Ident(t.Schema, t.Name)

	if t.PartitionOf != nil {
		if t.PartitionBound != nil {
			sql += " PARTITION OF " + *t.PartitionOf + " " + *t.PartitionBound
			if t.TableSpace != nil {
				sql += "\nTABLESPACE " + Ident(*t.TableSpace)
			}
			return sql + ";"
		} else {
			sql += "(\n" +
				strings.Join(
					orderedmap.TransformSlice(t.Constraints, func(_ string, con *Constraint) string {
						return "    CONSTRAINT " + Ident(con.Name) + " " + con.Definition
					}),
					",\n",
				) +
				")\n" +
				"INHERITS (" + *t.PartitionOf + ");"
			return sql
		}
	}

	sql += " (\n" +
		strings.Join(
			slices.Concat(
				orderedmap.TransformSlice(t.Columns, func(_ string, col *Column) string {
					q := "    " + Ident(col.Name) + " " + col.TypeName
					if col.Collation != nil {
						q += " COLLATE " + Ident(*col.Collation)
					}
					if col.Identity.IsGeneratedAlways() {
						q += " GENERATED ALWAYS AS IDENTITY"
					} else if col.Identity.IsGeneratedByDefault() {
						q += " GENERATED BY DEFAULT AS IDENTITY"
					} else if col.Generated.IsStoredGeneratedColumn() {
						if col.Default != nil {
							q += " GENERATED ALWAYS AS (" + *col.Default + ") STORED"
						}
					} else if col.Default != nil {
						q += " DEFAULT " + *col.Default
					}
					if col.NotNull && !col.Identity.IsIdentityColumn() {
						q += " NOT NULL"
					}
					return q
				}),
				orderedmap.TransformSlice(t.Constraints, func(_ string, con *Constraint) string {
					return "    CONSTRAINT " + Ident(con.Name) + " " + con.Definition
				}),
			),
			",\n",
		) +
		"\n)"

	if t.Partitioned && t.PartitionDef != nil {
		sql += "\nPARTITION BY " + *t.PartitionDef
	}

	if t.TableSpace != nil {
		sql += "\nTABLESPACE " + Ident(*t.TableSpace)
	}

	return sql + ";"
}

func (t Table) IdxSQL() string {
	return strings.Join(
		orderedmap.TransformSlice(t.Indexes, func(_ string, idx *Index) string { return idx.SQL() }),
		"\n",
	)
}

func (t Table) FkSQL() string {
	return strings.Join(
		orderedmap.TransformSlice(t.ForeignKeys, func(_ string, fk *ForeignKey) string { return fk.SQL() }),
		"\n",
	)
}

func (t Table) RLSSQL() string {
	var stmts []string
	if t.RowSecurity {
		stmts = append(stmts, "ALTER TABLE "+t.FQTN()+" ENABLE ROW LEVEL SECURITY;")
	}
	if t.ForceRowSecurity {
		stmts = append(stmts, "ALTER TABLE "+t.FQTN()+" FORCE ROW LEVEL SECURITY;")
	}
	if t.Policies != nil {
		for _, p := range t.Policies.CollectValues() {
			stmts = append(stmts, p.SQL())
		}
	}
	return strings.Join(stmts, "\n")
}

func (t Table) CommentSQL() string {
	var stmts []string
	if t.Comment != nil {
		stmts = append(stmts, "COMMENT ON TABLE "+Ident(t.Schema, t.Name)+" IS "+QuoteLiteral(*t.Comment)+";")
	}
	for _, col := range t.Columns.CollectValues() {
		if col.Comment != nil {
			stmts = append(stmts, "COMMENT ON COLUMN "+Ident(t.Schema, t.Name)+"."+Ident(col.Name)+" IS "+QuoteLiteral(*col.Comment)+";")
		}
	}
	return strings.Join(stmts, "\n")
}

func TableToSQL(t *Table) string {
	parts := []string{"-- " + t.FQTN(), t.SQL()}
	if s := t.IdxSQL(); s != "" {
		parts = append(parts, s)
	}
	if s := t.FkSQL(); s != "" {
		parts = append(parts, "\n"+s)
	}
	if s := t.RLSSQL(); s != "" {
		parts = append(parts, "\n"+s)
	}
	if s := t.CommentSQL(); s != "" {
		parts = append(parts, s)
	}
	return strings.Join(parts, "\n")
}

func TablesToSQL(tables *orderedmap.Map[string, *Table]) string {
	return strings.Join(
		orderedmap.TransformSlice(tables, func(_ string, t *Table) string {
			return TableToSQL(t)
		}),
		"\n\n",
	)
}
