package model

import (
	"slices"
	"strings"

	"github.com/winebarrel/orderedmap"
)

type Table struct {
	OID            uint32
	Schema         string
	Name           string
	RenameFrom     *string
	TableSpace     *string
	Unlogged       bool
	Partitioned    bool
	PartitionDef   *string
	PartitionOf    *string
	PartitionBound *string
	Columns        *orderedmap.Map[string, *Column]
	Constraints    *orderedmap.Map[string, *Constraint]
	ForeignKeys    *orderedmap.Map[string, *ForeignKey]
	Indexes        *orderedmap.Map[string, *Index]
	Comment        *string
}

func (t Table) FQTN() string {
	return Ident(t.Schema, t.Name)
}

func (t Table) SQL() string {
	sql := "CREATE "
	if t.Unlogged {
		sql += "UNLOGGED "
	}
	sql += "TABLE " + Ident(t.Schema, t.Name)

	if t.PartitionOf != nil {
		if t.PartitionBound != nil {
			sql += " PARTITION OF " + *t.PartitionOf + " " + *t.PartitionBound
			if t.TableSpace != nil {
				sql += "\nTABLESPACE " + Ident(*t.TableSpace)
			}
			return sql + ";"
		} else {
			sql += "(\n" +
				strings.Join(
					orderedmap.TransformSlice(t.Constraints, func(_ string, con *Constraint) string {
						return "    CONSTRAINT " + Ident(con.Name) + " " + con.Definition
					}),
					",\n",
				) +
				")\n" +
				"INHERITS (" + *t.PartitionOf + ");"
			return sql
		}
	}

	sql += " (\n" +
		strings.Join(
			slices.Concat(
				orderedmap.TransformSlice(t.Columns, func(_ string, col *Column) string {
					q := "    " + Ident(col.Name) + " " + col.TypeName
					if col.Collation != nil {
						q += " COLLATE " + Ident(*col.Collation)
					}
					if col.Identity.IsGeneratedAlways() {
						q += " GENERATED ALWAYS AS IDENTITY"
					} else if col.Identity.IsGeneratedByDefault() {
						q += " GENERATED BY DEFAULT AS IDENTITY"
					} else if col.Generated.IsStoredGeneratedColumn() {
						if col.Default != nil {
							q += " GENERATED ALWAYS AS (" + *col.Default + ") STORED"
						}
					} else if col.Default != nil {
						q += " DEFAULT " + *col.Default
					}
					if col.NotNull && !col.Identity.IsIdentityColumn() {
						q += " NOT NULL"
					}
					if col.RenameFrom != nil {
						q = "    -- pist:renamed-from " + *col.RenameFrom + "\n" + q
					}
					return q
				}),
				orderedmap.TransformSlice(t.Constraints, func(_ string, con *Constraint) string {
					q := "    CONSTRAINT " + Ident(con.Name) + " " + con.Definition
					if con.RenameFrom != nil {
						q = "    -- pist:renamed-from " + *con.RenameFrom + "\n" + q
					}
					return q
				}),
			),
			",\n",
		) +
		"\n)"

	if t.Partitioned && t.PartitionDef != nil {
		sql += "\nPARTITION BY " + *t.PartitionDef
	}

	if t.TableSpace != nil {
		sql += "\nTABLESPACE " + Ident(*t.TableSpace)
	}

	return sql + ";"
}

func (t Table) IdxSQL() string {
	return strings.Join(
		orderedmap.TransformSlice(t.Indexes, func(_ string, idx *Index) string {
			return withDirectives(idx.SQL(), renamedFromDirective(idx.RenameFrom), concurrentlyDirective(idx.Concurrently))
		}),
		"\n",
	)
}

func (t Table) FkSQL() string {
	return strings.Join(
		orderedmap.TransformSlice(t.ForeignKeys, func(_ string, fk *ForeignKey) string {
			return withDirectives(fk.SQL(), renamedFromDirective(fk.RenameFrom))
		}),
		"\n",
	)
}

func (t Table) CommentSQL() string {
	var stmts []string
	if t.Comment != nil {
		stmts = append(stmts, "COMMENT ON TABLE "+Ident(t.Schema, t.Name)+" IS "+QuoteLiteral(*t.Comment)+";")
	}
	for _, col := range t.Columns.CollectValues() {
		if col.Comment != nil {
			stmts = append(stmts, "COMMENT ON COLUMN "+Ident(t.Schema, t.Name)+"."+Ident(col.Name)+" IS "+QuoteLiteral(*col.Comment)+";")
		}
	}
	return strings.Join(stmts, "\n")
}

func TableToSQL(t *Table) string {
	return "-- " + t.FQTN() + "\n" + TableToSQLBare(t)
}

func TableToSQLBare(t *Table) string {
	parts := []string{withDirectives(t.SQL(), renamedFromDirective(t.RenameFrom))}
	if s := t.IdxSQL(); s != "" {
		parts = append(parts, s)
	}
	if s := t.FkSQL(); s != "" {
		parts = append(parts, "\n"+s)
	}
	if s := t.CommentSQL(); s != "" {
		parts = append(parts, s)
	}
	return strings.Join(parts, "\n")
}

func TablesToSQL(tables *orderedmap.Map[string, *Table]) string {
	return strings.Join(
		orderedmap.TransformSlice(tables, func(_ string, t *Table) string {
			return TableToSQL(t)
		}),
		"\n\n",
	)
}
