package model

import (
	"maps"
	"slices"
	"strings"

	"github.com/winebarrel/orderedmap/v2"
)

type Table struct {
	OID        uint32
	Schema     string
	Name       string
	RenameFrom *string
	BulkAlter  bool
	// Ignore marks the table as unmanaged (set by -- pista:ignore). Ignored
	// objects are not created, altered, or dropped; always false on the
	// catalog side.
	Ignore     bool
	TableSpace *string
	// StorageParams holds the table's storage parameters, pg_class.reloptions,
	// keyed by parameter name and ordered by it. A `toast.` prefix names a
	// parameter of the TOAST relation, which is where pg_dump writes it too.
	StorageParams    *orderedmap.Map[string, string]
	Unlogged         bool
	Partitioned      bool
	PartitionDef     *string
	PartitionOf      *string
	PartitionBound   *string
	RowSecurity      bool
	ForceRowSecurity bool
	Columns          *orderedmap.Map[string, *Column]
	Constraints      *orderedmap.Map[string, *Constraint]
	ForeignKeys      *orderedmap.Map[string, *ForeignKey]
	Indexes          *orderedmap.Map[string, *Index]
	Policies         *orderedmap.Map[string, *Policy]
	Triggers         *orderedmap.Map[string, *Trigger]
	Comment          *string
}

// IsPartitionChild reports whether the table is a partition of a declarative
// partitioned table. An INHERITS child also carries PartitionOf, but no bound,
// so the bound is what separates the two.
func (t Table) IsPartitionChild() bool {
	return t.PartitionOf != nil && t.PartitionBound != nil
}

// IsInheritsChild reports whether the table inherits from a parent without
// being a partition of it, which is the case the bound separates from the one
// IsPartitionChild reports. Such a child declares columns and constraints of
// its own alongside the ones it inherits, and both sides of the diff carry the
// local half alone: the catalog filters on attislocal and conislocal, and a
// desired schema names what the child's CREATE TABLE writes.
func (t Table) IsInheritsChild() bool {
	return t.PartitionOf != nil && t.PartitionBound == nil
}

func (t Table) FQTN() string {
	return Ident(t.Schema, t.Name)
}

func (t Table) SQL() string {
	sql := "CREATE "
	if t.Unlogged {
		sql += "UNLOGGED "
	}
	sql += "TABLE " + Ident(t.Schema, t.Name)

	if t.IsPartitionChild() {
		sql += " PARTITION OF " + *t.PartitionOf + " " + *t.PartitionBound
		if t.Partitioned && t.PartitionDef != nil {
			sql += "\nPARTITION BY " + *t.PartitionDef
		}
		if w := t.StorageParamsSQL(); w != "" {
			sql += "\n" + w
		}
		if t.TableSpace != nil {
			sql += "\nTABLESPACE " + Ident(*t.TableSpace)
		}
		return sql + ";"
	}

	defs := slices.Concat(
		t.Columns.TransformSlice(func(_ string, col *Column) string {
			q := "    " + Ident(col.Name) + " " + col.TypeName
			if col.Collation != nil {
				q += " COLLATE " + *col.Collation
			}
			if col.Identity.IsGeneratedAlways() {
				q += " GENERATED ALWAYS AS IDENTITY" + col.IdentitySeq.OptionsSQL(col.TypeName)
			} else if col.Identity.IsGeneratedByDefault() {
				q += " GENERATED BY DEFAULT AS IDENTITY" + col.IdentitySeq.OptionsSQL(col.TypeName)
			} else if col.Generated.IsStoredGeneratedColumn() {
				if col.Default != nil {
					q += " GENERATED ALWAYS AS (" + *col.Default + ") STORED"
				}
			} else if col.Default != nil {
				q += " DEFAULT " + *col.Default
			}
			if col.NotNull && !col.Identity.IsIdentityColumn() {
				if col.NotNullName != nil {
					q += " CONSTRAINT " + Ident(*col.NotNullName)
				}
				q += " NOT NULL"
			}
			return q
		}),
		t.inlineConstraintDefs(),
	)

	// An INHERITS child that declares nothing of its own writes the parentheses
	// empty, the way pg_dump does, rather than the blank line a join of no
	// elements would leave between them.
	if len(defs) == 0 {
		sql += " (\n)"
	} else {
		sql += " (\n" + strings.Join(defs, ",\n") + "\n)"
	}

	// The grammar takes INHERITS after the column list, so the child's own
	// declarations sit in the parentheses above and the parent follows them.
	if t.IsInheritsChild() {
		sql += "\nINHERITS (" + *t.PartitionOf + ")"
	}

	if t.Partitioned && t.PartitionDef != nil {
		sql += "\nPARTITION BY " + *t.PartitionDef
	}

	if w := t.StorageParamsSQL(); w != "" {
		sql += "\n" + w
	}

	if t.TableSpace != nil {
		sql += "\nTABLESPACE " + Ident(*t.TableSpace)
	}

	return sql + ";"
}

// inlineConstraintDefs renders the constraints written inside CREATE TABLE.
// A NOT VALID check is left out, since the clause cannot be spelled there and
// writing the constraint without it would restore it validated; NotValidConSQL
// adds it back.
func (t Table) inlineConstraintDefs() []string {
	var defs []string
	for _, con := range t.Constraints.CollectValues() {
		if con.Type.IsCheckConstraint() && !con.Validated {
			continue
		}
		defs = append(defs, "    CONSTRAINT "+Ident(con.Name)+" "+con.Definition)
	}
	return defs
}

// NotValidConSQL renders the table's NOT VALID check constraints, each as its
// own ALTER TABLE after the table. ONLY is dropped on a partitioned table,
// which rejects it once a partition exists. A partition child renders nothing:
// its unvalidated entries are the clones the parent's statement creates. An
// INHERITS child carries only its own constraints, so it renders them the way
// a plain table does; writing one inline would restore it validated.
func (t Table) NotValidConSQL() string {
	if t.IsPartitionChild() {
		return ""
	}
	only := "ONLY "
	if t.Partitioned {
		only = ""
	}
	var stmts []string
	for _, con := range t.Constraints.CollectValues() {
		if !con.Type.IsCheckConstraint() || con.Validated {
			continue
		}
		stmts = append(stmts, "ALTER TABLE "+only+t.FQTN()+" ADD CONSTRAINT "+Ident(con.Name)+" "+con.Definition+" NOT VALID;")
	}
	return strings.Join(stmts, "\n")
}

func (t Table) IdxSQL() string {
	return strings.Join(
		t.Indexes.TransformSlice(func(_ string, idx *Index) string { return idx.SQL() }),
		"\n",
	)
}

func (t Table) FkSQL() string {
	return strings.Join(
		t.ForeignKeys.TransformSlice(func(_ string, fk *ForeignKey) string { return fk.SQL() }),
		"\n",
	)
}

func (t Table) RLSSQL() string {
	var stmts []string
	if t.RowSecurity {
		stmts = append(stmts, "ALTER TABLE "+t.FQTN()+" ENABLE ROW LEVEL SECURITY;")
	}
	if t.ForceRowSecurity {
		stmts = append(stmts, "ALTER TABLE "+t.FQTN()+" FORCE ROW LEVEL SECURITY;")
	}
	if t.Policies != nil {
		for _, p := range t.Policies.CollectValues() {
			stmts = append(stmts, p.SQL())
		}
	}
	return strings.Join(stmts, "\n")
}

// TrigSQL renders the table's triggers, each followed by the ALTER TABLE that
// puts it in a non-default enable state.
func (t Table) TrigSQL() string {
	var stmts []string
	if t.Triggers != nil {
		for _, trg := range t.Triggers.CollectValues() {
			stmts = append(stmts, trg.SQL())
			if s := trg.StateSQL(); s != "" {
				stmts = append(stmts, s)
			}
		}
	}
	return strings.Join(stmts, "\n")
}

// SortedStorageParams turns a name -> value map of storage parameters into an
// ordered map keyed in name order, so neither the comparison nor the dump
// depends on the order a file or the catalog kept them in.
func SortedStorageParams(params map[string]string) *orderedmap.Map[string, string] {
	om := orderedmap.New[string, string]()
	for _, name := range slices.Sorted(maps.Keys(params)) {
		om.Set(name, params[name])
	}
	return om
}

// StorageParamsSQL renders the table's storage parameters as the WITH clause
// of a CREATE TABLE, or "" when it holds none. Every value is quoted.
// PostgreSQL accepts that for any parameter, so the renderer does not have to
// decide which spellings pass as a bare identifier.
func (t Table) StorageParamsSQL() string {
	if t.StorageParams == nil || t.StorageParams.Len() == 0 {
		return ""
	}
	return "WITH (" + strings.Join(
		t.StorageParams.TransformSlice(func(name, value string) string {
			return name + "=" + QuoteLiteral(value)
		}),
		", ",
	) + ")"
}

// SetStorageParamsSQL returns the statement that sets the named storage
// parameters. It does not rewrite the table.
func SetStorageParamsSQL(fqtn string, params []string) string {
	return "ALTER TABLE " + fqtn + " SET (" + strings.Join(params, ", ") + ");"
}

// ResetStorageParamsSQL returns the statement that hands the named storage
// parameters back to their defaults. RESET is the only way to say that: the
// catalog holds no entry for a parameter that was never set, so a SET has no
// default value to name.
func ResetStorageParamsSQL(fqtn string, names []string) string {
	return "ALTER TABLE " + fqtn + " RESET (" + strings.Join(names, ", ") + ");"
}

// SetStorageSQL returns the statement that puts a column's TOAST strategy at
// storage, one of the four keywords. It is a statement of its own because a
// column definition accepts STORAGE only from PostgreSQL 16 on.
func SetStorageSQL(fqtn, col, storage string) string {
	return "ALTER TABLE " + fqtn + " ALTER COLUMN " + Ident(col) + " SET STORAGE " + strings.ToUpper(storage) + ";"
}

// SetCompressionSQL returns the statement that puts a column's TOAST
// compression at compression. An empty method hands the column back to
// default_toast_compression.
func SetCompressionSQL(fqtn, col, compression string) string {
	if compression == "" {
		compression = "default"
	}
	return "ALTER TABLE " + fqtn + " ALTER COLUMN " + Ident(col) + " SET COMPRESSION " + compression + ";"
}

// StorageSQL renders the columns whose TOAST storage or compression is not the
// default. A partition child and an INHERITS child declare no columns of their
// own, and a partition copies both off the parent attribute as it is created,
// so neither is rendered.
func (t Table) StorageSQL() string {
	if t.PartitionOf != nil {
		return ""
	}
	var stmts []string
	for _, col := range t.Columns.CollectValues() {
		if col.StorageType != "" && col.StorageType != col.TypeStorage {
			stmts = append(stmts, SetStorageSQL(t.FQTN(), col.Name, col.StorageType))
		}
		if col.Compression != "" {
			stmts = append(stmts, SetCompressionSQL(t.FQTN(), col.Name, col.Compression))
		}
	}
	return strings.Join(stmts, "\n")
}

func (t Table) CommentSQL() string {
	var stmts []string
	if t.Comment != nil {
		stmts = append(stmts, "COMMENT ON TABLE "+Ident(t.Schema, t.Name)+" IS "+QuoteLiteral(*t.Comment)+";")
	}
	for _, col := range t.Columns.CollectValues() {
		if col.Comment != nil {
			stmts = append(stmts, "COMMENT ON COLUMN "+Ident(t.Schema, t.Name)+"."+Ident(col.Name)+" IS "+QuoteLiteral(*col.Comment)+";")
		}
	}
	return strings.Join(stmts, "\n")
}

func TableToSQL(t *Table) string {
	parts := []string{"-- " + t.FQTN(), t.SQL()}
	if s := t.NotValidConSQL(); s != "" {
		parts = append(parts, s)
	}
	if s := t.StorageSQL(); s != "" {
		parts = append(parts, s)
	}
	if s := t.IdxSQL(); s != "" {
		parts = append(parts, s)
	}
	if s := t.FkSQL(); s != "" {
		parts = append(parts, "\n"+s)
	}
	if s := t.RLSSQL(); s != "" {
		parts = append(parts, "\n"+s)
	}
	if s := t.TrigSQL(); s != "" {
		parts = append(parts, "\n"+s)
	}
	if s := t.CommentSQL(); s != "" {
		parts = append(parts, s)
	}
	return strings.Join(parts, "\n")
}

func TablesToSQL(tables *orderedmap.Map[string, *Table]) string {
	return strings.Join(
		tables.TransformSlice(func(_ string, t *Table) string {
			return TableToSQL(t)
		}),
		"\n\n",
	)
}
