package model

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/winebarrel/orderedmap"
)

func newTable(schema, name string) *Table {
	return &Table{
		Schema:      schema,
		Name:        name,
		Columns:     orderedmap.New[string, *Column](),
		Constraints: orderedmap.New[string, *Constraint](),
		ForeignKeys: orderedmap.New[string, *ForeignKey](),
		Indexes:     orderedmap.New[string, *Index](),
	}
}

func TestTable_FQTN(t *testing.T) {
	tbl := newTable("public", "users")
	assert.Equal(t, "public.users", tbl.FQTN())
}

func TestTable_SQL_simple(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.Columns.Set("id", &Column{Name: "id", TypeName: "integer", NotNull: true})
	tbl.Constraints.Set("users_pkey", &Constraint{Name: "users_pkey", Definition: "PRIMARY KEY (id)"})

	expected := `CREATE TABLE public.users (
    id integer NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);`
	assert.Equal(t, expected, tbl.SQL())
}

func TestTable_SQL_unlogged(t *testing.T) {
	tbl := newTable("public", "temp_data")
	tbl.Unlogged = true
	tbl.Columns.Set("id", &Column{Name: "id", TypeName: "integer"})

	assert.Contains(t, tbl.SQL(), "CREATE UNLOGGED TABLE")
}

func TestTable_SQL_withDefault(t *testing.T) {
	tbl := newTable("public", "users")
	def := "0"
	tbl.Columns.Set("age", &Column{Name: "age", TypeName: "integer", Default: &def})

	assert.Contains(t, tbl.SQL(), "DEFAULT 0")
}

func TestTable_SQL_withCollation(t *testing.T) {
	tbl := newTable("public", "users")
	coll := "en_US"
	tbl.Columns.Set("name", &Column{Name: "name", TypeName: "text", Collation: &coll})

	assert.Contains(t, tbl.SQL(), `COLLATE "en_US"`)
}

func TestTable_SQL_identityAlways(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.Columns.Set("id", &Column{Name: "id", TypeName: "integer", Identity: ColumnIdentity('a')})

	assert.Contains(t, tbl.SQL(), "GENERATED ALWAYS AS IDENTITY")
}

func TestTable_SQL_identityByDefault(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.Columns.Set("id", &Column{Name: "id", TypeName: "integer", Identity: ColumnIdentity('d')})

	assert.Contains(t, tbl.SQL(), "GENERATED BY DEFAULT AS IDENTITY")
}

func TestTable_SQL_generatedStored(t *testing.T) {
	tbl := newTable("public", "users")
	def := "first_name || ' ' || last_name"
	tbl.Columns.Set("full_name", &Column{
		Name:      "full_name",
		TypeName:  "text",
		Generated: ColumnGenerated('s'),
		Default:   &def,
	})

	sql := tbl.SQL()
	assert.Contains(t, sql, "GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED")
}

func TestTable_SQL_identityNotNull(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.Columns.Set("id", &Column{Name: "id", TypeName: "integer", NotNull: true, Identity: ColumnIdentity('a')})
	// Identity columns should NOT emit NOT NULL
	assert.NotContains(t, tbl.SQL(), "NOT NULL")
}

func TestTable_SQL_partitioned(t *testing.T) {
	tbl := newTable("public", "events")
	tbl.Partitioned = true
	partDef := "RANGE (created_at)"
	tbl.PartitionDef = &partDef
	tbl.Columns.Set("id", &Column{Name: "id", TypeName: "integer"})

	sql := tbl.SQL()
	assert.Contains(t, sql, "PARTITION BY RANGE (created_at)")
}

func TestTable_SQL_partitionOf_withBound(t *testing.T) {
	tbl := newTable("public", "events_2024")
	parent := "public.events"
	bound := "FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')"
	tbl.PartitionOf = &parent
	tbl.PartitionBound = &bound

	sql := tbl.SQL()
	assert.Contains(t, sql, "PARTITION OF public.events")
	assert.Contains(t, sql, "FOR VALUES FROM")
}

func TestTable_SQL_partitionOf_withBound_tablespace(t *testing.T) {
	tbl := newTable("public", "events_2024")
	parent := "public.events"
	bound := "FOR VALUES FROM ('2024-01-01') TO ('2025-01-01')"
	ts := "fast_ssd"
	tbl.PartitionOf = &parent
	tbl.PartitionBound = &bound
	tbl.TableSpace = &ts

	sql := tbl.SQL()
	assert.Contains(t, sql, "TABLESPACE fast_ssd")
}

func TestTable_SQL_partitionOf_inherits(t *testing.T) {
	tbl := newTable("public", "child")
	parent := "public.parent"
	tbl.PartitionOf = &parent
	tbl.Constraints.Set("child_pkey", &Constraint{Name: "child_pkey", Definition: "PRIMARY KEY (id)"})

	sql := tbl.SQL()
	assert.Contains(t, sql, "INHERITS (public.parent)")
	assert.Contains(t, sql, "CONSTRAINT child_pkey PRIMARY KEY (id)")
}

func TestTable_SQL_tablespace(t *testing.T) {
	tbl := newTable("public", "users")
	ts := "my_ts"
	tbl.TableSpace = &ts
	tbl.Columns.Set("id", &Column{Name: "id", TypeName: "integer"})

	assert.Contains(t, tbl.SQL(), "TABLESPACE my_ts")
}

func TestTable_IdxSQL(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.Indexes.Set("idx_name", &Index{Definition: "CREATE INDEX idx_name ON public.users USING btree (name)"})
	assert.Equal(t, "CREATE INDEX idx_name ON public.users USING btree (name);", tbl.IdxSQL())
}

func TestTable_IdxSQL_empty(t *testing.T) {
	tbl := newTable("public", "users")
	assert.Equal(t, "", tbl.IdxSQL())
}

func TestTable_FkSQL(t *testing.T) {
	tbl := newTable("public", "orders")
	tbl.ForeignKeys.Set("fk_user", &ForeignKey{
		Constraint: Constraint{Name: "fk_user", Definition: "FOREIGN KEY (user_id) REFERENCES public.users(id)", Validated: true},
		Schema:     "public",
		Table:      "orders",
	})
	assert.Contains(t, tbl.FkSQL(), "ALTER TABLE ONLY public.orders ADD CONSTRAINT fk_user")
}

func TestTable_CommentSQL(t *testing.T) {
	tbl := newTable("public", "users")
	comment := "Main users table"
	tbl.Comment = &comment
	colComment := "User name"
	tbl.Columns.Set("name", &Column{Name: "name", TypeName: "text", Comment: &colComment})

	sql := tbl.CommentSQL()
	assert.Contains(t, sql, "COMMENT ON TABLE public.users IS 'Main users table';")
	assert.Contains(t, sql, "COMMENT ON COLUMN public.users.name IS 'User name';")
}

func TestTable_CommentSQL_noComments(t *testing.T) {
	tbl := newTable("public", "users")
	tbl.Columns.Set("id", &Column{Name: "id", TypeName: "integer"})
	assert.Equal(t, "", tbl.CommentSQL())
}

func TestTablesToSQL(t *testing.T) {
	tables := orderedmap.New[string, *Table]()
	tbl := newTable("public", "users")
	tbl.Columns.Set("id", &Column{Name: "id", TypeName: "integer", NotNull: true})
	tbl.Constraints.Set("users_pkey", &Constraint{Name: "users_pkey", Definition: "PRIMARY KEY (id)"})
	tables.Set("public.users", tbl)

	got := TablesToSQL(tables)
	assert.Contains(t, got, "-- public.users")
	assert.Contains(t, got, "CREATE TABLE public.users")
}
