version: "2"
linters:
  enable:
    - asasalint
    - durationcheck
    - errorlint
    - fatcontext
    - makezero
    - nilerr
    - nilnesserr
    - reassign
    - testifylint
    - unconvert
    - usestdlibvars
    - wastedassign
  exclusions:
    rules:
      - linters:
          - errcheck
        path: _test\.go
formatters:
  enable:
    - gofumpt
    - goimports
