package diff

import (
	"fmt"
	"strings"

	pg_query "github.com/pganalyze/pg_query_go/v6"
	"github.com/winebarrel/orderedmap"
	"github.com/winebarrel/pistachio/model"
	"google.golang.org/protobuf/proto"
)

func DiffTables(current, desired *orderedmap.Map[string, *model.Table]) []string {
	var stmts []string

	// New tables
	for k, v := range desired.All() {
		if _, ok := current.GetOk(k); !ok {
			stmts = append(stmts, v.SQL())
			stmts = append(stmts, newTableExtras(v)...)
		}
	}

	// Modified tables
	for k, desiredTable := range desired.All() {
		if currentTable, ok := current.GetOk(k); ok {
			stmts = append(stmts, diffTable(currentTable, desiredTable)...)
		}
	}

	// Dropped tables
	for k := range current.Keys() {
		if _, ok := desired.GetOk(k); !ok {
			stmts = append(stmts, "DROP TABLE "+k+";")
		}
	}

	return stmts
}

func newTableExtras(t *model.Table) []string {
	var stmts []string
	for _, idx := range t.Indexes.CollectValues() {
		stmts = append(stmts, idx.SQL())
	}
	for _, fk := range t.ForeignKeys.CollectValues() {
		stmts = append(stmts, fk.SQL())
	}
	if commentSQL := t.CommentSQL(); commentSQL != "" {
		stmts = append(stmts, strings.Split(commentSQL, "\n")...)
	}
	return stmts
}

func diffTable(current, desired *model.Table) []string {
	var stmts []string
	fqtn := desired.FQTN()

	// Partition children inherit columns and constraints from the parent,
	// so skip diffing them to avoid false DROP statements.
	if desired.PartitionOf != nil && desired.PartitionBound != nil {
		stmts = append(stmts, diffIndexes(current.Indexes, desired.Indexes)...)
		stmts = append(stmts, diffForeignKeys(fqtn, current.ForeignKeys, desired.ForeignKeys)...)
		return stmts
	}

	stmts = append(stmts, diffColumns(fqtn, current.Columns, desired.Columns)...)
	stmts = append(stmts, diffConstraints(fqtn, current.Constraints, desired.Constraints)...)
	stmts = append(stmts, diffIndexes(current.Indexes, desired.Indexes)...)
	stmts = append(stmts, diffForeignKeys(fqtn, current.ForeignKeys, desired.ForeignKeys)...)
	stmts = append(stmts, diffComments(current, desired)...)

	return stmts
}

func diffColumns(fqtn string, current, desired *orderedmap.Map[string, *model.Column]) []string {
	var stmts []string

	// Add new columns
	for name, col := range desired.All() {
		if _, ok := current.GetOk(name); !ok {
			stmts = append(stmts, addColumnSQL(fqtn, col))
		}
	}

	// Alter existing columns
	for name, desiredCol := range desired.All() {
		if currentCol, ok := current.GetOk(name); ok {
			stmts = append(stmts, alterColumnSQL(fqtn, currentCol, desiredCol)...)
		}
	}

	// Drop removed columns
	for name := range current.Keys() {
		if _, ok := desired.GetOk(name); !ok {
			stmts = append(stmts, "ALTER TABLE "+fqtn+" DROP COLUMN "+model.Ident(name)+";")
		}
	}

	return stmts
}

func addColumnSQL(fqtn string, col *model.Column) string {
	sql := "ALTER TABLE " + fqtn + " ADD COLUMN " + model.Ident(col.Name) + " " + col.TypeName

	if col.Collation != nil {
		sql += " COLLATE " + model.Ident(*col.Collation)
	}

	if col.Identity.IsGeneratedAlways() {
		sql += " GENERATED ALWAYS AS IDENTITY"
	} else if col.Identity.IsGeneratedByDefault() {
		sql += " GENERATED BY DEFAULT AS IDENTITY"
	} else if col.Generated.IsStoredGeneratedColumn() {
		if col.Default != nil {
			sql += " GENERATED ALWAYS AS (" + *col.Default + ") STORED"
		}
	} else if col.Default != nil {
		sql += " DEFAULT " + *col.Default
	}

	if col.NotNull && !col.Identity.IsIdentityColumn() {
		sql += " NOT NULL"
	}

	return sql + ";"
}

func alterColumnSQL(fqtn string, current, desired *model.Column) []string {
	var stmts []string
	colIdent := model.Ident(desired.Name)

	// Type change
	if !equalTypeName(current.TypeName, desired.TypeName) {
		sql := "ALTER TABLE " + fqtn + " ALTER COLUMN " + colIdent + " SET DATA TYPE " + desired.TypeName
		if desired.Collation != nil {
			sql += " COLLATE " + model.Ident(*desired.Collation)
		}
		stmts = append(stmts, sql+";")
	}

	// Default change
	if !equalDefault(current.Default, desired.Default) {
		if desired.Default != nil {
			stmts = append(stmts, "ALTER TABLE "+fqtn+" ALTER COLUMN "+colIdent+" SET DEFAULT "+*desired.Default+";")
		} else {
			stmts = append(stmts, "ALTER TABLE "+fqtn+" ALTER COLUMN "+colIdent+" DROP DEFAULT;")
		}
	}

	// NOT NULL change
	// Identity columns are implicitly NOT NULL in PostgreSQL; skip NOT NULL diff
	// when either side is an identity column to avoid spurious SET/DROP NOT NULL.
	if current.NotNull != desired.NotNull && !current.Identity.IsIdentityColumn() && !desired.Identity.IsIdentityColumn() {
		if desired.NotNull {
			stmts = append(stmts, "ALTER TABLE "+fqtn+" ALTER COLUMN "+colIdent+" SET NOT NULL;")
		} else {
			stmts = append(stmts, "ALTER TABLE "+fqtn+" ALTER COLUMN "+colIdent+" DROP NOT NULL;")
		}
	}

	return stmts
}

func diffConstraints(fqtn string, current, desired *orderedmap.Map[string, *model.Constraint]) []string {
	var stmts []string

	// Drop removed or changed constraints
	for name, currentCon := range current.All() {
		desiredCon, ok := desired.GetOk(name)
		if !ok || currentCon.Definition != desiredCon.Definition {
			stmts = append(stmts, "ALTER TABLE "+fqtn+" DROP CONSTRAINT "+model.Ident(name)+";")
		}
	}

	// Add new or changed constraints
	for name, desiredCon := range desired.All() {
		currentCon, ok := current.GetOk(name)
		if !ok || currentCon.Definition != desiredCon.Definition {
			stmts = append(stmts, "ALTER TABLE "+fqtn+" ADD CONSTRAINT "+model.Ident(name)+" "+desiredCon.Definition+";")
		}
	}

	return stmts
}

func diffIndexes(current, desired *orderedmap.Map[string, *model.Index]) []string {
	var stmts []string

	// Drop removed or changed indexes
	for name, currentIdx := range current.All() {
		desiredIdx, ok := desired.GetOk(name)
		if !ok || !equalIndexDef(currentIdx.Definition, desiredIdx.Definition) {
			stmts = append(stmts, "DROP INDEX "+model.Ident(currentIdx.Schema, name)+";")
		}
	}

	// Add new or changed indexes
	for name, desiredIdx := range desired.All() {
		currentIdx, ok := current.GetOk(name)
		if !ok || !equalIndexDef(currentIdx.Definition, desiredIdx.Definition) {
			stmts = append(stmts, desiredIdx.Definition+";")
		}
	}

	return stmts
}

func diffForeignKeys(fqtn string, current, desired *orderedmap.Map[string, *model.ForeignKey]) []string {
	var stmts []string

	// Drop removed or changed FKs
	for name := range current.All() {
		desiredFk, ok := desired.GetOk(name)
		currentFk := current.Get(name)
		if !ok || !equalFKDef(currentFk.Definition, desiredFk.Definition) {
			stmts = append(stmts, "ALTER TABLE "+fqtn+" DROP CONSTRAINT "+model.Ident(name)+";")
		}
	}

	// Add new or changed FKs
	for name, desiredFk := range desired.All() {
		currentFk, ok := current.GetOk(name)
		if !ok || !equalFKDef(currentFk.Definition, desiredFk.Definition) {
			stmts = append(stmts, desiredFk.SQL())
		}
	}

	return stmts
}

func diffComments(current, desired *model.Table) []string {
	var stmts []string
	fqtn := desired.FQTN()

	// Table comment
	if !equalPtr(current.Comment, desired.Comment) {
		if desired.Comment != nil {
			stmts = append(stmts, "COMMENT ON TABLE "+fqtn+" IS "+model.QuoteLiteral(*desired.Comment)+";")
		} else {
			stmts = append(stmts, "COMMENT ON TABLE "+fqtn+" IS NULL;")
		}
	}

	// Column comments
	for name, desiredCol := range desired.Columns.All() {
		var currentComment *string
		if currentCol, ok := current.Columns.GetOk(name); ok {
			currentComment = currentCol.Comment
		}
		if !equalPtr(currentComment, desiredCol.Comment) {
			colIdent := fqtn + "." + model.Ident(name)
			if desiredCol.Comment != nil {
				stmts = append(stmts, "COMMENT ON COLUMN "+colIdent+" IS "+model.QuoteLiteral(*desiredCol.Comment)+";")
			} else {
				stmts = append(stmts, "COMMENT ON COLUMN "+colIdent+" IS NULL;")
			}
		}
	}

	return stmts
}

func equalPtr[T comparable](a, b *T) bool {
	if a == nil && b == nil {
		return true
	}
	if a == nil || b == nil {
		return false
	}
	return *a == *b
}

// parseIndexDef parses an index definition string into a pg_query IndexStmt node.
func parseIndexDef(def string) (*pg_query.IndexStmt, error) {
	result, err := pg_query.Parse(def)
	if err != nil {
		return nil, err
	}
	is := result.Stmts[0].Stmt.GetIndexStmt()
	if is == nil {
		return nil, fmt.Errorf("unexpected parse result for index definition: %s", def)
	}
	return is, nil
}

// clearIndexSchema clears the schema name in an IndexStmt so that
// index definitions are compared without regard to schema qualification.
func clearIndexSchema(is *pg_query.IndexStmt) {
	if is.Relation != nil {
		is.Relation.Schemaname = ""
	}
}

// equalIndexDef compares two index definitions by their parse trees,
// so that schema qualification differences do not cause false diffs.
func equalIndexDef(a, b string) bool {
	nodeA, errA := parseIndexDef(a)
	nodeB, errB := parseIndexDef(b)
	if errA != nil || errB != nil {
		return a == b
	}
	clearIndexSchema(nodeA)
	clearIndexSchema(nodeB)
	return proto.Equal(nodeA, nodeB)
}

// parseFKDef parses a FK constraint definition string into a pg_query Constraint node.
func parseFKDef(def string) (*pg_query.Constraint, error) {
	sql := "ALTER TABLE _t ADD CONSTRAINT _c " + def
	result, err := pg_query.Parse(sql)
	if err != nil {
		return nil, err
	}
	as := result.Stmts[0].Stmt.GetAlterTableStmt()
	if as == nil {
		return nil, fmt.Errorf("unexpected parse result for FK definition: %s", def)
	}
	cmd := as.Cmds[0].GetAlterTableCmd()
	if cmd == nil {
		return nil, fmt.Errorf("unexpected parse result for FK definition: %s", def)
	}
	con := cmd.Def.GetConstraint()
	if con == nil {
		return nil, fmt.Errorf("unexpected parse result for FK definition: %s", def)
	}
	return con, nil
}

// normalizeFKSchema normalizes the referenced table's schema name in a FK
// constraint node so that an empty schema (implicit public) is treated
// the same as an explicit "public" schema.
func normalizeFKSchema(con *pg_query.Constraint) {
	if con.Pktable != nil && con.Pktable.Schemaname == "" {
		con.Pktable.Schemaname = "public"
	}
}

// equalFKDef compares two FK constraint definitions by their parse trees,
// so that formatting differences do not cause false diffs.
func equalFKDef(a, b string) bool {
	nodeA, errA := parseFKDef(a)
	nodeB, errB := parseFKDef(b)
	if errA != nil || errB != nil {
		return a == b
	}
	normalizeFKSchema(nodeA)
	normalizeFKSchema(nodeB)
	return proto.Equal(nodeA, nodeB)
}

// parseDefault parses a default expression string into a pg_query Node,
// stripping a top-level type cast added by pg_get_expr (e.g. 'hello'::text → 'hello').
func parseDefault(expr string) (*pg_query.Node, error) {
	result, err := pg_query.Parse("SELECT " + expr)
	if err != nil {
		return nil, err
	}
	stmt := result.Stmts[0].Stmt.GetSelectStmt()
	if stmt == nil || len(stmt.TargetList) == 0 {
		return nil, fmt.Errorf("unexpected parse result for default: %s", expr)
	}
	target := stmt.TargetList[0].GetResTarget()
	if target == nil {
		return nil, fmt.Errorf("unexpected parse result for default: %s", expr)
	}
	node := target.Val
	// Strip top-level type cast added by pg_get_expr
	if node.GetTypeCast() != nil {
		node = node.GetTypeCast().Arg
	}
	return node, nil
}

// serialBaseTypes maps serial type names to their base types.
var serialBaseTypes = map[string]string{
	"serial":      "integer",
	"bigserial":   "bigint",
	"smallserial": "smallint",
}

// equalTypeName compares two type names, treating serial types as equal to their base types.
func equalTypeName(a, b string) bool {
	if a == b {
		return true
	}
	normalize := func(t string) string {
		if base, ok := serialBaseTypes[t]; ok {
			return base
		}
		return t
	}
	return normalize(a) == normalize(b)
}

// equalDefault compares two default expressions by their parse trees.
func equalDefault(a, b *string) bool {
	if a == nil && b == nil {
		return true
	}
	if a == nil || b == nil {
		return false
	}
	nodeA, errA := parseDefault(*a)
	nodeB, errB := parseDefault(*b)
	if errA != nil || errB != nil {
		return *a == *b
	}
	return proto.Equal(nodeA, nodeB)
}
