-- No SEQUENCE NAME: pistachio does not manage the name of the sequence behind
-- an identity column, so one renamed by hand restores under the default name.
-- TODO.md records it.
CREATE TABLE public.tickets (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5 MINVALUE 10 MAXVALUE 1000 CACHE 20 CYCLE),
    down bigint GENERATED ALWAYS AS IDENTITY (INCREMENT BY -1),
    plain integer GENERATED ALWAYS AS IDENTITY,
    small_id smallserial NOT NULL,
    ser_id serial NOT NULL,
    CONSTRAINT tickets_pkey PRIMARY KEY (id)
);
