-- No sequence options on the identity column: model.Column carries the
-- GENERATED ALWAYS / BY DEFAULT flag alone, so INCREMENT BY and the rest are
-- restored at their defaults. TODO.md records it.
CREATE TABLE public.tickets (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    small_id smallserial NOT NULL,
    ser_id serial NOT NULL,
    CONSTRAINT tickets_pkey PRIMARY KEY (id)
);
