package catalog_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/winebarrel/pistachio/catalog"
	"github.com/winebarrel/pistachio/internal/testutil"
)

func TestListColumnsByTable(t *testing.T) {
	ctx := context.Background()
	conn := testutil.ConnectDB(t)
	defer conn.Close(ctx)

	t.Run("basic types", func(t *testing.T) {
		testutil.SetupDB(t, ctx, conn, `
			CREATE TABLE public.users (
				id integer NOT NULL,
				name text NOT NULL,
				email text,
				CONSTRAINT users_pkey PRIMARY KEY (id)
			);
		`)
		cat, err := catalog.NewCatalog(conn, []string{"public"})
		require.NoError(t, err)
		tables, err := cat.Tables(ctx)
		require.NoError(t, err)

		tbl := tables.Get("public.users")
		require.NotNil(t, tbl)

		id, ok := tbl.Columns.GetOk("id")
		require.True(t, ok)
		assert.Equal(t, "integer", id.TypeName)
		assert.True(t, id.NotNull)
		assert.Nil(t, id.Default)

		name, ok := tbl.Columns.GetOk("name")
		require.True(t, ok)
		assert.Equal(t, "text", name.TypeName)
		assert.True(t, name.NotNull)

		email, ok := tbl.Columns.GetOk("email")
		require.True(t, ok)
		assert.Equal(t, "text", email.TypeName)
		assert.False(t, email.NotNull)
	})

	t.Run("with default", func(t *testing.T) {
		testutil.SetupDB(t, ctx, conn, `
			CREATE TABLE public.users (
				id integer NOT NULL,
				name text DEFAULT 'unknown' NOT NULL,
				CONSTRAINT users_pkey PRIMARY KEY (id)
			);
		`)
		cat, err := catalog.NewCatalog(conn, []string{"public"})
		require.NoError(t, err)
		tables, err := cat.Tables(ctx)
		require.NoError(t, err)

		tbl := tables.Get("public.users")
		name, ok := tbl.Columns.GetOk("name")
		require.True(t, ok)
		require.NotNil(t, name.Default)
		assert.Equal(t, "'unknown'::text", *name.Default)
	})

	t.Run("serial", func(t *testing.T) {
		testutil.SetupDB(t, ctx, conn, `
			CREATE TABLE public.users (
				id serial NOT NULL,
				CONSTRAINT users_pkey PRIMARY KEY (id)
			);
		`)
		cat, err := catalog.NewCatalog(conn, []string{"public"})
		require.NoError(t, err)
		tables, err := cat.Tables(ctx)
		require.NoError(t, err)

		tbl := tables.Get("public.users")
		id, ok := tbl.Columns.GetOk("id")
		require.True(t, ok)
		assert.Equal(t, "serial", id.TypeName)
		assert.Nil(t, id.Default)
	})

	t.Run("bigserial", func(t *testing.T) {
		testutil.SetupDB(t, ctx, conn, `
			CREATE TABLE public.users (
				id bigserial NOT NULL,
				CONSTRAINT users_pkey PRIMARY KEY (id)
			);
		`)
		cat, err := catalog.NewCatalog(conn, []string{"public"})
		require.NoError(t, err)
		tables, err := cat.Tables(ctx)
		require.NoError(t, err)

		tbl := tables.Get("public.users")
		id, ok := tbl.Columns.GetOk("id")
		require.True(t, ok)
		assert.Equal(t, "bigserial", id.TypeName)
		assert.Nil(t, id.Default)
	})

	t.Run("smallserial", func(t *testing.T) {
		testutil.SetupDB(t, ctx, conn, `
			CREATE TABLE public.users (
				id smallserial NOT NULL,
				CONSTRAINT users_pkey PRIMARY KEY (id)
			);
		`)
		cat, err := catalog.NewCatalog(conn, []string{"public"})
		require.NoError(t, err)
		tables, err := cat.Tables(ctx)
		require.NoError(t, err)

		tbl := tables.Get("public.users")
		id, ok := tbl.Columns.GetOk("id")
		require.True(t, ok)
		assert.Equal(t, "smallserial", id.TypeName)
		assert.Nil(t, id.Default)
	})

	t.Run("identity always", func(t *testing.T) {
		testutil.SetupDB(t, ctx, conn, `
			CREATE TABLE public.items (
				id integer GENERATED ALWAYS AS IDENTITY,
				CONSTRAINT items_pkey PRIMARY KEY (id)
			);
		`)
		cat, err := catalog.NewCatalog(conn, []string{"public"})
		require.NoError(t, err)
		tables, err := cat.Tables(ctx)
		require.NoError(t, err)

		tbl := tables.Get("public.items")
		id, ok := tbl.Columns.GetOk("id")
		require.True(t, ok)
		assert.Equal(t, "integer", id.TypeName)
		assert.True(t, id.Identity.IsGeneratedAlways())
	})

	t.Run("identity by default", func(t *testing.T) {
		testutil.SetupDB(t, ctx, conn, `
			CREATE TABLE public.items (
				id integer GENERATED BY DEFAULT AS IDENTITY,
				CONSTRAINT items_pkey PRIMARY KEY (id)
			);
		`)
		cat, err := catalog.NewCatalog(conn, []string{"public"})
		require.NoError(t, err)
		tables, err := cat.Tables(ctx)
		require.NoError(t, err)

		tbl := tables.Get("public.items")
		id, ok := tbl.Columns.GetOk("id")
		require.True(t, ok)
		assert.Equal(t, "integer", id.TypeName)
		assert.True(t, id.Identity.IsGeneratedByDefault())
	})

	t.Run("column comment", func(t *testing.T) {
		testutil.SetupDB(t, ctx, conn, `
			CREATE TABLE public.users (
				id integer NOT NULL,
				name text NOT NULL,
				CONSTRAINT users_pkey PRIMARY KEY (id)
			);
			COMMENT ON COLUMN public.users.name IS 'Full name';
		`)
		cat, err := catalog.NewCatalog(conn, []string{"public"})
		require.NoError(t, err)
		tables, err := cat.Tables(ctx)
		require.NoError(t, err)

		tbl := tables.Get("public.users")
		name, ok := tbl.Columns.GetOk("name")
		require.True(t, ok)
		require.NotNil(t, name.Comment)
		assert.Equal(t, "Full name", *name.Comment)
	})

	t.Run("collation", func(t *testing.T) {
		testutil.SetupDB(t, ctx, conn, `
			CREATE TABLE public.users (
				id integer NOT NULL,
				name text COLLATE "C" NOT NULL,
				CONSTRAINT users_pkey PRIMARY KEY (id)
			);
		`)
		cat, err := catalog.NewCatalog(conn, []string{"public"})
		require.NoError(t, err)
		tables, err := cat.Tables(ctx)
		require.NoError(t, err)

		tbl := tables.Get("public.users")
		name, ok := tbl.Columns.GetOk("name")
		require.True(t, ok)
		require.NotNil(t, name.Collation)
		assert.Equal(t, "C", *name.Collation)
	})

	t.Run("generated column", func(t *testing.T) {
		testutil.SetupDB(t, ctx, conn, `
			CREATE TABLE public.products (
				id integer NOT NULL,
				price numeric(10,2) NOT NULL,
				tax numeric(10,2) NOT NULL,
				total numeric(10,2) GENERATED ALWAYS AS (price + tax) STORED,
				CONSTRAINT products_pkey PRIMARY KEY (id)
			);
		`)
		cat, err := catalog.NewCatalog(conn, []string{"public"})
		require.NoError(t, err)
		tables, err := cat.Tables(ctx)
		require.NoError(t, err)

		tbl := tables.Get("public.products")
		total, ok := tbl.Columns.GetOk("total")
		require.True(t, ok)
		assert.True(t, total.Generated.IsStoredGeneratedColumn())
	})

	t.Run("various types", func(t *testing.T) {
		testutil.SetupDB(t, ctx, conn, `
			CREATE TABLE public.types_test (
				col_bool boolean,
				col_int2 smallint,
				col_int4 integer,
				col_int8 bigint,
				col_float4 real,
				col_float8 double precision,
				col_numeric numeric(10,2),
				col_varchar character varying(255),
				col_text text,
				col_date date,
				col_timestamp timestamp without time zone,
				col_timestamptz timestamp with time zone,
				col_uuid uuid,
				col_json json,
				col_jsonb jsonb,
				col_bytea bytea,
				col_int_array integer[]
			);
		`)
		cat, err := catalog.NewCatalog(conn, []string{"public"})
		require.NoError(t, err)
		tables, err := cat.Tables(ctx)
		require.NoError(t, err)

		tbl := tables.Get("public.types_test")
		require.NotNil(t, tbl)

		cases := map[string]string{
			"col_bool":        "boolean",
			"col_int2":        "smallint",
			"col_int4":        "integer",
			"col_int8":        "bigint",
			"col_float4":      "real",
			"col_float8":      "double precision",
			"col_numeric":     "numeric(10,2)",
			"col_varchar":     "character varying(255)",
			"col_text":        "text",
			"col_date":        "date",
			"col_timestamp":   "timestamp without time zone",
			"col_timestamptz": "timestamp with time zone",
			"col_uuid":        "uuid",
			"col_json":        "json",
			"col_jsonb":       "jsonb",
			"col_bytea":       "bytea",
			"col_int_array":   "integer[]",
		}
		for colName, expectedType := range cases {
			col, ok := tbl.Columns.GetOk(colName)
			require.True(t, ok, "column %s not found", colName)
			assert.Equal(t, expectedType, col.TypeName, "column %s", colName)
		}
	})
}
